import type { StorybookConfig } from '@storybook/react-vite'
import tailwindcss from '@tailwindcss/vite'
import { mergeConfig } from 'vite'

const config: StorybookConfig = {
  stories: [
    // `.storybook/*.mdx` intro/landing docs (e.g. Foundations.mdx).
    './**/*.mdx',
    '../src/**/*.stories.@(ts|tsx)',
  ],
  // `addon-docs` powers the autogenerated Docs tab (preview.tsx sets the
  // `autodocs` tag) and compiles `.mdx` landing pages like Foundations.mdx.
  // `addon-a11y` provides the accessibility panel AND the axe check that
  // `addon-vitest` runs per story (see preview.tsx `parameters.a11y.test`).
  // `addon-vitest` turns every story into a Vitest browser-mode test — it is
  // what replaced `@storybook/test-runner` as the a11y/render-smoke gate.
  addons: ['@storybook/addon-a11y', '@storybook/addon-docs', '@storybook/addon-vitest'],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  // Storybook runs its own Vite pipeline, so the Tailwind plugin from
  // vite.config.ts isn't picked up automatically. Without this hook,
  // `@import 'tailwindcss'` in src/styles/index.css is a no-op and stories
  // render unstyled — making visual regression baselines meaningless.
  viteFinal: async (config) =>
    mergeConfig(config, {
      plugins: [tailwindcss()],
      optimizeDeps: {
        // Pre-bundle React + the Radix primitives so portal/overlay content
        // mounted during interaction (`play`) tests resolves a single shared
        // React instance, rather than lazy-loading a second copy mid-test
        // (which crashes with "Cannot read properties of null (reading
        // 'useRef')" in Vitest browser mode).
        include: [
          'react',
          'react-dom',
          'react-dom/client',
          'react/jsx-runtime',
          'react/jsx-dev-runtime',
          '@radix-ui/react-accordion',
          '@radix-ui/react-alert-dialog',
          '@radix-ui/react-avatar',
          '@radix-ui/react-checkbox',
          '@radix-ui/react-collapsible',
          '@radix-ui/react-dialog',
          '@radix-ui/react-dropdown-menu',
          '@radix-ui/react-label',
          '@radix-ui/react-popover',
          '@radix-ui/react-radio-group',
          '@radix-ui/react-select',
          '@radix-ui/react-separator',
          '@radix-ui/react-slot',
          '@radix-ui/react-tabs',
          '@radix-ui/react-tooltip',
        ],
      },
    }),
}

export default config
