import type { StorybookConfig } from '@storybook/react-vite'
import tailwindcss from '@tailwindcss/vite'

const config: StorybookConfig = {
  stories: [
    // `.storybook/*.mdx` intro/landing docs (e.g. Foundations.mdx).
    './**/*.mdx',
    '../src/**/*.stories.@(ts|tsx)',
  ],
  // `addon-docs` powers the autogenerated Docs tab (preview.tsx sets the
  // `autodocs` tag) and compiles `.mdx` landing pages like Foundations.mdx.
  // `addon-a11y` keeps the accessibility panel.
  addons: ['@storybook/addon-a11y', '@storybook/addon-docs'],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  // Storybook runs its own Vite pipeline, so the Tailwind plugin from
  // vite.config.ts isn't picked up automatically. Without this hook,
  // `@import 'tailwindcss'` in src/styles/index.css is a no-op and stories
  // render unstyled — making visual regression baselines meaningless.
  viteFinal: async (config) => {
    config.plugins = [...(config.plugins ?? []), tailwindcss()]
    return config
  },
}

export default config
